# included:
#     - Sources

# rule identifiers to exclude from running
disabled_rules:
- type_name
- line_length



# configurable rules can be customized from this configuration file
line_length: 250
function_body_length:
  warning: 50
